# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.1.0
_src_path: https://github.com/jupyterlab/extension-template
has_binder: true
has_settings: false
kind: frontend
labextension_name: lc_run_through
project_short_description: A JupyterLab extension.
python_name: lc_run_through
repository: https://github.com/NII-cloud-operation/Jupyter-LC_run_through.git
test: false

